# Generated by Django 4.1.6 on 2023-02-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name_plural': 'Pontos turísticos'},
        ),
    ]
