# Generated by Django 4.1.6 on 2023-02-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontoturistico_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='Endereco',
            new_name='endereco',
        ),
    ]
