# Generated by Django 4.1.6 on 2023-02-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursos',
            options={'verbose_name_plural': 'recursos'},
        ),
    ]
