# Generated by Django 4.1.6 on 2023-02-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_alter_endereco_linha2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereços'},
        ),
    ]
